import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1791032572068 implements MigrationInterface {
    name = 'InitialSchema1791032572068'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // BASELINE: the full schema as it was when migrations were introduced
        // (2026-10-03). Staging and production were created earlier by
        // TypeORM "synchronize", so their tables already exist - in that
        // case this migration only gets marked as applied and changes
        // nothing. On a brand-new empty database it creates everything.
        if (await queryRunner.hasTable('users')) {
            console.log('[InitialSchema] Existing database detected - baseline marked as applied, no changes made.');
            return;
        }
        await queryRunner.query(`CREATE TABLE \`tax_payments\` (\`id\` varchar(36) NOT NULL, \`paymentNumber\` varchar(255) NOT NULL, \`period\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`datePaid\` date NOT NULL, \`reference\` varchar(255) NULL, \`note\` text NULL, \`documentFilePath\` varchar(255) NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_886c0411c81a617b6a8e38ad72\` (\`paymentNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendor_prepayment_applications\` (\`id\` varchar(36) NOT NULL, \`vendorPrepaymentId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`purchaseOrderId\` varchar(255) NULL, \`note\` text NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendor_prepayments\` (\`id\` varchar(36) NOT NULL, \`prepaymentNumber\` varchar(255) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`bankAccountId\` varchar(255) NOT NULL, \`bankTransactionId\` varchar(255) NULL, \`appliedAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`note\` text NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4dcb77a8094596f90b1c88248a\` (\`prepaymentNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendor_credit_applications\` (\`id\` varchar(36) NOT NULL, \`vendorCreditId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`purchaseOrderId\` varchar(255) NULL, \`note\` text NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendor_credit_refunds\` (\`id\` varchar(36) NOT NULL, \`vendorCreditId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`bankAccountId\` varchar(255) NOT NULL, \`bankTransactionId\` varchar(255) NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`vendor_credits\` (\`id\` varchar(36) NOT NULL, \`creditNumber\` varchar(255) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`reason\` text NULL, \`appliedAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`refundedAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d65de484001a2e7d1a3b35bb87\` (\`creditNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`suppliers\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`contactPerson\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`address\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier_payments\` (\`id\` varchar(36) NOT NULL, \`purchaseOrderId\` varchar(255) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`paymentType\` enum ('cash', 'bank_transfer', 'card_machine', 'cheque', 'conditional') NULL, \`paymentDate\` date NOT NULL, \`note\` text NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier_interactions\` (\`id\` varchar(36) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`type\` enum ('call', 'meeting', 'email', 'whatsapp', 'note', 'other') NOT NULL DEFAULT 'note', \`subject\` varchar(255) NULL, \`notes\` text NULL, \`interactionDate\` date NOT NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier_documents\` (\`id\` varchar(36) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`docType\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`supplier_bank_accounts\` (\`id\` varchar(36) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`accountName\` varchar(255) NULL, \`accountNumber\` varchar(255) NULL, \`bankName\` varchar(255) NULL, \`branchName\` varchar(255) NULL, \`branchCode\` varchar(255) NULL, \`swiftCode\` varchar(255) NULL, \`iban\` varchar(255) NULL, \`statementOriginalName\` varchar(255) NULL, \`statementPath\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tax_rates\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`rate\` decimal(6,3) NOT NULL, \`description\` text NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_return_items\` (\`id\` varchar(36) NOT NULL, \`purchaseReturnId\` varchar(255) NOT NULL, \`rawMaterialId\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`costPerUnit\` decimal(12,3) NOT NULL, \`vatRate\` decimal(6,3) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_returns\` (\`id\` varchar(36) NOT NULL, \`returnNumber\` varchar(255) NOT NULL, \`purchaseOrderId\` varchar(255) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`date\` date NOT NULL, \`reason\` text NULL, \`subtotal\` decimal(12,3) NOT NULL, \`vatAmount\` decimal(12,3) NOT NULL, \`total\` decimal(12,3) NOT NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`requestedByUserId\` varchar(255) NULL, \`requestedByEmail\` varchar(255) NULL, \`decidedByUserId\` varchar(255) NULL, \`decidedByEmail\` varchar(255) NULL, \`decidedAt\` datetime NULL, \`rejectionReason\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_448bb11c381cb6275453a448f3\` (\`returnNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_orders\` (\`id\` varchar(36) NOT NULL, \`supplierId\` varchar(255) NOT NULL, \`status\` enum ('ordered', 'received', 'cancelled') NOT NULL DEFAULT 'ordered', \`notes\` varchar(255) NULL, \`receivedAt\` datetime NULL, \`subtotal\` decimal(12,3) NULL, \`vatAmount\` decimal(12,3) NULL, \`total\` decimal(12,3) NULL, \`paidAmount\` decimal(12,3) NULL, \`paymentStatus\` enum ('paid', 'partial', 'due') NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`purchase_order_items\` (\`id\` varchar(36) NOT NULL, \`purchaseOrderId\` varchar(255) NOT NULL, \`rawMaterialId\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`costPerUnit\` decimal(12,3) NOT NULL, \`vatRate\` decimal(6,3) NOT NULL DEFAULT '5.000', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`logoPath\` varchar(255) NULL, \`companyName\` varchar(255) NOT NULL DEFAULT 'ARIBS Palm Peat', \`companyVatin\` varchar(255) NULL, \`companyAddress\` varchar(255) NULL, \`companyPhone\` varchar(255) NULL, \`defaultInvoiceTemplate\` enum ('classic', 'formal', 'po_style') NOT NULL DEFAULT 'classic', \`weeklyOffDays\` varchar(255) NULL, \`shiftStartTime\` time NULL, \`shiftEndTime\` time NULL, \`attendanceGraceMinutes\` int NOT NULL DEFAULT '15', \`incomeTaxRatePercent\` decimal(5,2) NOT NULL DEFAULT '15.00', \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company_documents\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_orders\` (\`id\` varchar(36) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`status\` enum ('pending', 'completed', 'cancelled') NOT NULL DEFAULT 'pending', \`paymentType\` enum ('cash', 'bank_transfer', 'card_machine', 'cheque', 'conditional') NULL, \`paymentStatus\` enum ('paid', 'partial', 'due') NOT NULL DEFAULT 'due', \`notes\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_order_items\` (\`id\` varchar(36) NOT NULL, \`salesOrderId\` varchar(255) NOT NULL, \`finishedGoodId\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`unitPrice\` decimal(12,3) NOT NULL, \`vatRate\` decimal(5,2) NOT NULL DEFAULT '5.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_batch_consumptions\` (\`id\` varchar(36) NOT NULL, \`salesOrderId\` varchar(255) NULL, \`finishedGoodBatchId\` varchar(255) NOT NULL, \`finishedGoodId\` varchar(255) NOT NULL, \`quantityConsumed\` decimal(12,3) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reimbursements\` (\`id\` varchar(36) NOT NULL, \`claimNumber\` varchar(255) NOT NULL, \`employeeId\` varchar(255) NOT NULL, \`category\` enum ('travel', 'meals', 'office_supplies', 'medical', 'other') NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`description\` text NULL, \`invoiceNumber\` varchar(255) NULL, \`receiptFilePath\` varchar(255) NULL, \`status\` enum ('pending', 'approved', 'rejected', 'paid') NOT NULL DEFAULT 'pending', \`requestedByUserId\` varchar(255) NULL, \`requestedByEmail\` varchar(255) NULL, \`decidedByUserId\` varchar(255) NULL, \`decidedByEmail\` varchar(255) NULL, \`decidedAt\` datetime NULL, \`rejectionReason\` text NULL, \`paymentMethod\` varchar(255) NULL, \`paymentNote\` text NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`paidAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_bda04c97f367d1915a02900a16\` (\`claimNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`recurring_invoices\` (\`id\` varchar(36) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`label\` varchar(255) NOT NULL, \`items\` text NOT NULL, \`discountAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`paymentType\` enum ('cash', 'bank_transfer', 'card_machine', 'cheque', 'conditional') NULL, \`deliveryMethod\` enum ('on_site', 'in_store') NULL, \`template\` enum ('classic', 'formal', 'po_style') NULL, \`vatExcluded\` tinyint NULL, \`dueDays\` int NULL, \`frequency\` enum ('weekly', 'monthly', 'quarterly', 'yearly') NOT NULL, \`startDate\` date NOT NULL, \`nextRunDate\` date NOT NULL, \`endDate\` date NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`lastGeneratedInvoiceId\` varchar(255) NULL, \`lastRunAt\` date NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quotations\` (\`id\` varchar(36) NOT NULL, \`sequenceNumber\` int NOT NULL AUTO_INCREMENT, \`quotationNumber\` varchar(255) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`issueDate\` date NOT NULL, \`validUntil\` date NULL, \`subtotal\` decimal(12,3) NOT NULL, \`discountAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`deliveryMethod\` enum ('on_site', 'in_store') NULL, \`vatAmount\` decimal(12,3) NOT NULL, \`total\` decimal(12,3) NOT NULL, \`status\` enum ('draft', 'approved', 'converted', 'expired') NOT NULL DEFAULT 'draft', \`invoiceId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d8f932b6ab373aa2ba38e20ede\` (\`sequenceNumber\`), UNIQUE INDEX \`IDX_1abd99974f3059c04df9104a76\` (\`quotationNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quotation_items\` (\`id\` varchar(36) NOT NULL, \`quotationId\` varchar(255) NOT NULL, \`finishedGoodId\` varchar(255) NULL, \`description\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`unitPrice\` decimal(12,3) NOT NULL, \`vatRate\` decimal(5,2) NOT NULL DEFAULT '5.00', \`lineTotal\` decimal(12,3) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`quotation_edit_requests\` (\`id\` varchar(36) NOT NULL, \`quotationId\` varchar(255) NOT NULL, \`proposedItems\` text NOT NULL, \`proposedValidUntil\` date NULL, \`proposedDiscountAmount\` decimal(12,3) NULL, \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`requestedByUserId\` varchar(255) NULL, \`requestedByEmail\` varchar(255) NULL, \`approvedByUserId\` varchar(255) NULL, \`approvedByEmail\` varchar(255) NULL, \`decidedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`production_orders\` (\`id\` varchar(36) NOT NULL, \`finishedGoodId\` varchar(255) NOT NULL, \`quantityToProduce\` decimal(12,3) NOT NULL, \`status\` enum ('planned', 'completed', 'cancelled') NOT NULL DEFAULT 'planned', \`notes\` varchar(255) NULL, \`completedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`production_batch_consumptions\` (\`id\` varchar(36) NOT NULL, \`productionOrderId\` varchar(255) NOT NULL, \`finishedGoodBatchId\` varchar(255) NOT NULL, \`rawMaterialBatchId\` varchar(255) NOT NULL, \`rawMaterialId\` varchar(255) NOT NULL, \`quantityConsumed\` decimal(12,3) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bill_of_materials\` (\`id\` varchar(36) NOT NULL, \`finishedGoodId\` varchar(255) NOT NULL, \`rawMaterialId\` varchar(255) NOT NULL, \`quantityPerUnit\` decimal(12,4) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`journal_entry_lines\` (\`id\` varchar(36) NOT NULL, \`journalEntryId\` varchar(255) NOT NULL, \`accountId\` varchar(255) NOT NULL, \`debit\` decimal(12,3) NOT NULL DEFAULT '0.000', \`credit\` decimal(12,3) NOT NULL DEFAULT '0.000', \`description\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`journal_entries\` (\`id\` varchar(36) NOT NULL, \`entryNumber\` varchar(255) NOT NULL, \`date\` date NOT NULL, \`reference\` varchar(255) NULL, \`memo\` text NOT NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`autoPosted\` tinyint NOT NULL DEFAULT 0, \`sourceType\` varchar(255) NULL, \`sourceId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4b3b30432878ce7cc7882e919b\` (\`entryNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`accounts\` (\`id\` varchar(36) NOT NULL, \`code\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('asset', 'liability', 'equity', 'revenue', 'expense') NOT NULL, \`description\` text NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_490319656e54a7957dc1fed027\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_return_items\` (\`id\` varchar(36) NOT NULL, \`salesReturnId\` varchar(255) NOT NULL, \`finishedGoodId\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`unitPrice\` decimal(12,3) NOT NULL, \`vatRate\` decimal(6,3) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sales_returns\` (\`id\` varchar(36) NOT NULL, \`returnNumber\` varchar(255) NOT NULL, \`invoiceId\` varchar(255) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`date\` date NOT NULL, \`reason\` text NULL, \`subtotal\` decimal(12,3) NOT NULL, \`vatAmount\` decimal(12,3) NOT NULL, \`total\` decimal(12,3) NOT NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`requestedByUserId\` varchar(255) NULL, \`requestedByEmail\` varchar(255) NULL, \`decidedByUserId\` varchar(255) NULL, \`decidedByEmail\` varchar(255) NULL, \`decidedAt\` datetime NULL, \`rejectionReason\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_1c9e9093e5e44ce769feec5be9\` (\`returnNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoices\` (\`id\` varchar(36) NOT NULL, \`sequenceNumber\` int NOT NULL AUTO_INCREMENT, \`invoiceNumber\` varchar(255) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`salesOrderId\` varchar(255) NULL, \`quotationId\` varchar(255) NULL, \`quotationNumber\` varchar(255) NULL, \`issueDate\` date NOT NULL, \`dueDate\` date NULL, \`deliveryDate\` date NULL, \`subtotal\` decimal(12,3) NOT NULL, \`discountAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`vatAmount\` decimal(12,3) NOT NULL, \`total\` decimal(12,3) NOT NULL, \`vatExcluded\` tinyint NOT NULL DEFAULT 0, \`paymentType\` enum ('cash', 'bank_transfer', 'card_machine', 'cheque', 'conditional') NULL, \`deliveryMethod\` enum ('on_site', 'in_store') NULL, \`paymentStatus\` enum ('paid', 'partial', 'due') NOT NULL DEFAULT 'due', \`paidAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`version\` int NOT NULL DEFAULT '1', \`template\` enum ('classic', 'formal', 'po_style') NOT NULL DEFAULT 'classic', \`pdfPath\` varchar(255) NULL, \`lastReminderSentAt\` date NULL, \`lastReminderMilestone\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4368f3a97bd0e6982b124ffc96\` (\`sequenceNumber\`), UNIQUE INDEX \`IDX_bf8e0f9dd4558ef209ec111782\` (\`invoiceNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoice_payments\` (\`id\` varchar(36) NOT NULL, \`invoiceId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`paymentType\` enum ('cash', 'bank_transfer', 'card_machine', 'cheque', 'conditional') NULL, \`paymentDate\` date NOT NULL, \`note\` text NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`invoice_items\` (\`id\` varchar(36) NOT NULL, \`invoiceId\` varchar(255) NOT NULL, \`finishedGoodId\` varchar(255) NULL, \`description\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`unitPrice\` decimal(12,3) NOT NULL, \`vatRate\` decimal(5,2) NOT NULL DEFAULT '5.00', \`lineTotal\` decimal(12,3) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`raw_materials\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`sku\` varchar(255) NULL, \`barcode\` varchar(255) NULL, \`unit\` varchar(255) NOT NULL, \`quantityInStock\` decimal(12,3) NOT NULL DEFAULT '0.000', \`lowStockThreshold\` decimal(12,3) NOT NULL DEFAULT '0.000', \`costPerUnit\` decimal(12,3) NOT NULL DEFAULT '0.000', \`supplierId\` varchar(255) NULL, \`reorderQuantity\` decimal(12,3) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_562177f2182ecfcfa260090f8d\` (\`sku\`), UNIQUE INDEX \`IDX_eaf032b7897abfdc74a00b0fab\` (\`barcode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`raw_material_batches\` (\`id\` varchar(36) NOT NULL, \`rawMaterialId\` varchar(255) NOT NULL, \`batchNumber\` varchar(255) NOT NULL, \`quantityReceived\` decimal(12,3) NOT NULL, \`quantityRemaining\` decimal(12,3) NOT NULL, \`costPerUnit\` decimal(12,3) NOT NULL, \`source\` enum ('purchase_order', 'production_order', 'manual', 'opening_balance') NOT NULL, \`purchaseOrderId\` varchar(255) NULL, \`supplierId\` varchar(255) NULL, \`notes\` varchar(255) NULL, \`receivedDate\` date NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_8a69802d8cc431eca8435f9b26\` (\`batchNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`finished_goods\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`sku\` varchar(255) NULL, \`barcode\` varchar(255) NOT NULL, \`unit\` varchar(255) NOT NULL, \`quantityInStock\` decimal(12,3) NOT NULL DEFAULT '0.000', \`lowStockThreshold\` decimal(12,3) NOT NULL DEFAULT '0.000', \`sellingPrice\` decimal(12,3) NOT NULL DEFAULT '0.000', \`costPerUnit\` decimal(12,3) NOT NULL DEFAULT '0.000', \`vatRate\` decimal(5,2) NOT NULL DEFAULT '5.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_0c10aac15720f044ed48f913da\` (\`sku\`), UNIQUE INDEX \`IDX_e33ce51ff55303854c72fc52bc\` (\`barcode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`finished_good_batches\` (\`id\` varchar(36) NOT NULL, \`finishedGoodId\` varchar(255) NOT NULL, \`batchNumber\` varchar(255) NOT NULL, \`quantityProduced\` decimal(12,3) NOT NULL, \`quantityRemaining\` decimal(12,3) NOT NULL, \`source\` enum ('purchase_order', 'production_order', 'manual', 'opening_balance') NOT NULL, \`productionOrderId\` varchar(255) NULL, \`producedDate\` date NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_bd63b4925e2486731de0310c1f\` (\`batchNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_teams\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d9b9865fc202662c52921b849f\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_shifts\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`startTime\` time NOT NULL, \`endTime\` time NOT NULL, \`lateTime\` time NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`salary_advance_requests\` (\`id\` varchar(36) NOT NULL, \`employeeId\` varchar(255) NULL, \`employeeName\` varchar(255) NOT NULL, \`amount\` decimal(10,3) NOT NULL, \`reason\` text NOT NULL, \`status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`approvalRequestId\` varchar(255) NULL, \`requestedByUserId\` varchar(255) NULL, \`requestedByEmail\` varchar(255) NULL, \`decidedByUserId\` varchar(255) NULL, \`decidedByEmail\` varchar(255) NULL, \`decidedAt\` datetime NULL, \`disbursed\` tinyint NOT NULL DEFAULT 0, \`disbursedDate\` date NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_roles\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_850a099a4421ca4e05800334f9\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_projects\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`startedOn\` date NULL, \`members\` varchar(255) NULL, \`tags\` varchar(255) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_payroll\` (\`id\` varchar(36) NOT NULL, \`employeeId\` varchar(255) NULL, \`staffName\` varchar(255) NOT NULL, \`periodFrom\` date NOT NULL, \`periodTo\` date NOT NULL, \`workingDays\` int NOT NULL DEFAULT '0', \`presentDays\` decimal(6,1) NOT NULL DEFAULT '0.0', \`absentDays\` int NOT NULL DEFAULT '0', \`workingHours\` decimal(7,2) NOT NULL DEFAULT '0.00', \`otHours\` decimal(7,2) NOT NULL DEFAULT '0.00', \`otRate\` decimal(10,2) NOT NULL DEFAULT '0.00', \`otPay\` decimal(10,2) NOT NULL DEFAULT '0.00', \`staffSalary\` decimal(10,2) NOT NULL DEFAULT '0.00', \`salaryPaidBy\` varchar(255) NULL, \`isPaid\` tinyint NOT NULL DEFAULT 0, \`paidDate\` date NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`calculatedSalary\` decimal(10,2) NOT NULL DEFAULT '0.00', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payroll_documents\` (\`id\` varchar(36) NOT NULL, \`payrollId\` varchar(255) NOT NULL, \`label\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_notices\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`date\` date NOT NULL, \`description\` varchar(255) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_leave_requests\` (\`id\` varchar(36) NOT NULL, \`title\` varchar(255) NULL, \`staffName\` varchar(255) NOT NULL, \`shortDescription\` varchar(255) NULL, \`date\` date NOT NULL, \`requestFrom\` date NOT NULL, \`requestTo\` date NOT NULL, \`leaves\` int NOT NULL DEFAULT '1', \`status\` enum ('pending', 'approved', 'canceled') NOT NULL DEFAULT 'pending', \`manageBy\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_holidays\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`dateFrom\` date NOT NULL, \`dateTo\` date NOT NULL, \`days\` int NOT NULL DEFAULT '1', \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_events\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` varchar(255) NULL, \`date\` date NOT NULL, \`time\` varchar(255) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employees\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`role\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`staffId\` varchar(255) NULL, \`department\` varchar(255) NULL, \`team\` varchar(255) NULL, \`shift\` varchar(255) NULL, \`baseSalary\` decimal(10,2) NULL, \`otRatePerHour\` decimal(10,2) NULL, \`biometricId\` varchar(255) NULL, \`photoPath\` varchar(255) NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`joinedDate\` date NULL, \`employmentType\` varchar(255) NOT NULL DEFAULT 'permanent', \`status\` varchar(255) NOT NULL DEFAULT 'working', \`archiveType\` varchar(255) NULL, \`archivedAt\` timestamp NULL, \`fatherName\` varchar(255) NULL, \`motherName\` varchar(255) NULL, \`birthDate\` date NULL, \`passportNumber\` varchar(255) NULL, \`nationality\` varchar(255) NULL, \`originCountryIdNumber\` varchar(255) NULL, \`homeAddress\` text NULL, \`educationalQualifications\` text NULL, \`skills\` text NULL, \`certifications\` text NULL, \`guardianName\` varchar(255) NULL, \`guardianPhone\` varchar(255) NULL, \`guardianNationalId\` varchar(255) NULL, \`guardianRelationship\` varchar(255) NULL, \`guardianAddress\` text NULL, \`emergencyPhone1\` varchar(255) NULL, \`emergencyPhone2\` varchar(255) NULL, \`guardianPhotoPath\` varchar(255) NULL, \`nomineeName\` varchar(255) NULL, \`nomineeNationalId\` varchar(255) NULL, \`nomineePhone\` varchar(255) NULL, \`nomineeRelationship\` varchar(255) NULL, \`nomineePhotoPath\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4fd0a18ba7c500cc91f8ec6e9c\` (\`biometricId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`employee_documents\` (\`id\` varchar(36) NOT NULL, \`employeeId\` varchar(255) NOT NULL, \`label\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_designations\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`department\` varchar(255) NULL, \`color\` varchar(255) NOT NULL DEFAULT '#4f46e5', \`active\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`hr_departments\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`otRatePerHour\` decimal(10,2) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_2d8b98e426d379152a16aa06e6\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attendance_records\` (\`id\` varchar(36) NOT NULL, \`employeeId\` varchar(255) NOT NULL, \`date\` date NOT NULL, \`checkIn\` time NULL, \`checkOut\` time NULL, \`lunchIn\` time NULL, \`lunchOut\` time NULL, \`breakMinutes\` int NULL, \`status\` enum ('present', 'absent', 'late', 'half_day', 'leave', 'weekend') NOT NULL DEFAULT 'present', \`notes\` varchar(255) NULL, \`overtimeHours\` decimal(5,2) NULL, \`source\` varchar(255) NOT NULL DEFAULT 'manual', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fixed_assets\` (\`id\` varchar(36) NOT NULL, \`assetNumber\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`category\` enum ('machinery_equipment', 'furniture_fixtures', 'vehicles', 'computer_office_equipment', 'other') NOT NULL, \`purchaseDate\` date NOT NULL, \`cost\` decimal(12,3) NOT NULL, \`salvageValue\` decimal(12,3) NOT NULL DEFAULT '0.000', \`usefulLifeMonths\` int NOT NULL, \`accumulatedDepreciation\` decimal(12,3) NOT NULL DEFAULT '0.000', \`lastDepreciationPeriod\` varchar(255) NULL, \`status\` enum ('active', 'disposed') NOT NULL DEFAULT 'active', \`disposalDate\` date NULL, \`disposalProceeds\` decimal(12,3) NULL, \`bankAccountId\` varchar(255) NULL, \`notes\` text NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_3a51a8242a3a1b76f4bd128bc8\` (\`assetNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`delivery_notes\` (\`id\` varchar(36) NOT NULL, \`sequenceNumber\` int NOT NULL AUTO_INCREMENT, \`deliveryNoteNumber\` varchar(255) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`issueDate\` date NOT NULL, \`deliveryDate\` date NULL, \`subtotal\` decimal(12,3) NOT NULL DEFAULT '0.000', \`discountAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`vatAmount\` decimal(12,3) NOT NULL DEFAULT '0.000', \`total\` decimal(12,3) NOT NULL DEFAULT '0.000', \`paymentType\` enum ('cash', 'bank_transfer', 'card_machine', 'cheque', 'conditional') NULL, \`deliveryMethod\` enum ('on_site', 'in_store') NULL, \`status\` enum ('draft', 'delivered') NOT NULL DEFAULT 'draft', \`invoiceNumber\` varchar(255) NULL, \`quotationNumber\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_b4240a4874ba919c1d187af226\` (\`sequenceNumber\`), UNIQUE INDEX \`IDX_a15e1b336a427fcbedeb36c953\` (\`deliveryNoteNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`delivery_note_items\` (\`id\` varchar(36) NOT NULL, \`deliveryNoteId\` varchar(255) NOT NULL, \`finishedGoodId\` varchar(255) NULL, \`description\` varchar(255) NOT NULL, \`quantity\` decimal(12,3) NOT NULL, \`unitPrice\` decimal(12,3) NOT NULL DEFAULT '0.000', \`vatRate\` decimal(5,2) NOT NULL DEFAULT '5.00', \`lineTotal\` decimal(12,3) NOT NULL DEFAULT '0.000', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`address\` varchar(255) NULL, \`crNumber\` varchar(255) NULL, \`vatin\` varchar(255) NULL, \`vatApplicable\` tinyint NOT NULL DEFAULT 1, \`creditLimit\` decimal(12,3) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_interactions\` (\`id\` varchar(36) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`type\` enum ('call', 'meeting', 'email', 'whatsapp', 'note', 'other') NOT NULL DEFAULT 'note', \`subject\` varchar(255) NULL, \`notes\` text NULL, \`interactionDate\` date NOT NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_documents\` (\`id\` varchar(36) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`docType\` varchar(255) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`filePath\` varchar(255) NOT NULL, \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_bank_accounts\` (\`id\` varchar(36) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`accountName\` varchar(255) NULL, \`accountNumber\` varchar(255) NULL, \`bankName\` varchar(255) NULL, \`branchName\` varchar(255) NULL, \`branchCode\` varchar(255) NULL, \`swiftCode\` varchar(255) NULL, \`iban\` varchar(255) NULL, \`statementOriginalName\` varchar(255) NULL, \`statementPath\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fund_transfers\` (\`id\` varchar(36) NOT NULL, \`transferNumber\` varchar(255) NOT NULL, \`fromAccountId\` varchar(255) NOT NULL, \`toAccountId\` varchar(255) NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`note\` text NULL, \`status\` enum ('completed', 'in_transit') NOT NULL DEFAULT 'completed', \`clearedDate\` date NULL, \`documentFilePath\` varchar(255) NULL, \`fromTransactionId\` varchar(255) NULL, \`toTransactionId\` varchar(255) NULL, \`createdByUserId\` varchar(255) NULL, \`createdByEmail\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_0c8dcfb4d2597da42770d75af6\` (\`transferNumber\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bank_transactions\` (\`id\` varchar(36) NOT NULL, \`bankAccountId\` varchar(255) NOT NULL, \`type\` enum ('deposit', 'withdrawal') NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`note\` varchar(255) NULL, \`category\` enum ('owners_contribution', 'other_income', 'opening_balance', 'owners_draw', 'bank_charges', 'other_expense') NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bank_accounts\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`type\` enum ('bank', 'cash') NOT NULL DEFAULT 'bank', \`bankName\` varchar(255) NULL, \`accountNumber\` varchar(255) NULL, \`openingBalance\` decimal(12,3) NOT NULL DEFAULT '0.000', \`currentBalance\` decimal(12,3) NOT NULL DEFAULT '0.000', \`journalAccountId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`passwordHash\` varchar(255) NOT NULL, \`role\` enum ('admin', 'ceo', 'md', 'accountant', 'production', 'sales') NOT NULL DEFAULT 'sales', \`active\` tinyint NOT NULL DEFAULT 1, \`modulePermissions\` text NULL, \`deletedAt\` timestamp NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`approval_requests\` (\`id\` varchar(36) NOT NULL, \`type\` enum ('credit_limit_override', 'large_discount', 'vat_exclude', 'salary_advance') NOT NULL, \`entityType\` varchar(255) NOT NULL, \`targetId\` varchar(255) NULL, \`customerId\` varchar(255) NULL, \`payload\` text NOT NULL, \`reason\` text NOT NULL, \`status\` enum ('pending', 'processing', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`requestedByUserId\` varchar(255) NULL, \`requestedByEmail\` varchar(255) NULL, \`approvedByUserId\` varchar(255) NULL, \`approvedByEmail\` varchar(255) NULL, \`decidedAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activity_logs\` (\`id\` varchar(36) NOT NULL, \`userId\` varchar(255) NULL, \`userEmail\` varchar(255) NULL, \`action\` varchar(255) NOT NULL, \`entityType\` varchar(255) NULL, \`entityId\` varchar(255) NULL, \`details\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_597e6df96098895bf19d4b5ea4\` (\`userId\`), INDEX \`IDX_a3d5764d4b44970698381dc664\` (\`entityType\`), INDEX \`IDX_377463c364326082e86ce68ed3\` (\`entityId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expenses\` (\`id\` varchar(36) NOT NULL, \`category\` enum ('rent', 'utilities', 'salary', 'raw_material', 'maintenance', 'transport', 'other') NOT NULL, \`amount\` decimal(12,3) NOT NULL, \`date\` date NOT NULL, \`description\` varchar(255) NULL, \`vendorName\` varchar(255) NULL, \`invoiceNumber\` varchar(255) NULL, \`invoiceFilePath\` varchar(255) NULL, \`bankAccountId\` varchar(255) NULL, \`bankTransactionId\` varchar(255) NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`vendor_prepayment_applications\` ADD CONSTRAINT \`FK_e27f95974e5bc8e3af2420b7bc6\` FOREIGN KEY (\`vendorPrepaymentId\`) REFERENCES \`vendor_prepayments\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vendor_credit_applications\` ADD CONSTRAINT \`FK_b32eebed7a5b47192f492107d34\` FOREIGN KEY (\`vendorCreditId\`) REFERENCES \`vendor_credits\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vendor_credit_refunds\` ADD CONSTRAINT \`FK_d777b2b625259f6cd14f55210d6\` FOREIGN KEY (\`vendorCreditId\`) REFERENCES \`vendor_credits\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`purchase_return_items\` ADD CONSTRAINT \`FK_7c0ccb18970b1a9ba216b901523\` FOREIGN KEY (\`purchaseReturnId\`) REFERENCES \`purchase_returns\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`journal_entry_lines\` ADD CONSTRAINT \`FK_b06b5322d679be6e2559132857d\` FOREIGN KEY (\`journalEntryId\`) REFERENCES \`journal_entries\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sales_return_items\` ADD CONSTRAINT \`FK_0d23c72f04c35424ea4ba275df1\` FOREIGN KEY (\`salesReturnId\`) REFERENCES \`sales_returns\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(_queryRunner: QueryRunner): Promise<void> {
        // Reverting the baseline would DROP EVERY TABLE and all data, so it
        // is intentionally disabled. Restore from a backup instead.
        throw new Error('The InitialSchema baseline cannot be reverted (it would delete all data).');
    }

}
